substitutions:
  _AWS_PRIVATE_IP: "3.101.31.181"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Pre-Requisites (clone repo + set permissions)
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Run Pre-Requisites'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir -p /root/.ssh
      echo "$$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      ssh-keyscan -H "$_AWS_PRIVATE_IP" >> /root/.ssh/known_hosts
      ssh -o StrictHostKeyChecking=no ubuntu@$_AWS_PRIVATE_IP << 'EOF'
        rm -rf /home/ubuntu/Udemy-section*
        git clone https://github.com/sagarkakkalasworld/Udemy-section9
        cd Udemy-section9
        chmod 744 /home/ubuntu/Udemy-section9/build.sh
        chmod 744 /home/ubuntu/Udemy-section9/deploy.sh
      EOF
  secretEnv: ['SSH_KEY']


# Step 3: Build App
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Build App'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir -p /root/.ssh
      echo "$$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      ssh-keyscan -H "$_AWS_PRIVATE_IP" >> /root/.ssh/known_hosts
      ssh -o StrictHostKeyChecking=no ubuntu@$_AWS_PRIVATE_IP "bash /home/ubuntu/Udemy-section9/build.sh"
  secretEnv: ['SSH_KEY']
  volumes:


# Step 4: Deploy App
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy App'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir -p /root/.ssh
      echo "$$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      ssh-keyscan -H "$_AWS_PRIVATE_IP" >> /root/.ssh/known_hosts
      ssh -o StrictHostKeyChecking=no ubuntu@$_AWS_PRIVATE_IP "bash /home/ubuntu/Udemy-section9/deploy.sh"
  secretEnv: ['SSH_KEY']



availableSecrets:
  secretManager:
    - versionName: projects/381798847413/secrets/SSH_KEY/versions/latest
      env: 'SSH_KEY'
